// packages/vue-test-app/src/App.vue
<script setup lang="ts">
  import { RouterView } from 'vue-router'
</script>

<template>
  <header>
    <h1>Windmolens zijn wij</h1>
  </header>

  <RouterView />
</template>

<style>
  @import "../../web-library/src/lib/brand-b-tokens.css";

  body {
    padding: 2rem;
    font-family: "Montserrat", sans-serif;
    font-optical-sizing: auto;
    font-weight: 400;
    font-style: normal;
    background: var(--brand-color-surface);
    color: var(--brand-color-on-surface);
  }
</style>

// packages/react-test-app/src/App.tsx
import "../../web-library/src/lib/brand-a-tokens.css"
import { defineCustomElements, WebMfe } from 'react-library';

defineCustomElements();

function App() {

  return (
    <>
      <header>
        <h1>Energie netwerks zijn wij</h1>
      </header>
      <WebMfe></WebMfe>
    </>
  )
}

export default App
